### ISSUE TITLE
Faulty CRC computation

### ISSUE THREAD

**Issue by MBjoern** [sparkfun/SparkFun_SCD30_Arduino_Library#16]
The interface for `setForcedRecalibrationFactor` is not working.
I assume that the CRC computation used in the sendCommand function is faulty, as I'd expect the checksum to be 0x50, but the code here is getting a 0x33.
Hence the forced recalibration is never executed on the chip.

Surprisingly, the other checksums are correct, only this one seams to be affected.

**Comment by nseidle** [comment]
Do you have some simple code that can demonstrate your issue?

**Comment by awatterott** [comment]
I can confirm that `setForcedRecalibrationFactor()` is working. Maybe the issue is related when the function is called to fast after power-up. The datasheet says that at least 2 minutes in a stable environment are needed and from our experiences it is not working or has no effect, when the time is too short.

**Comment by PaulZC** [comment]
Hi @MBjoern ,
Are you still having problems with ```setForcedRecalibrationFactor```?
Best wishes,
Paul

**Comment by MBjoern** [comment]
Hi Paul

Thank you for getting back to me. I did not manage to further test the issue. I've just noticed the discrepancy w.r.t. the CRC value.
If the library works for others, then it appears to be a problem on my end. This issue can be closed accordingly. Thank you.
